#!/bin/bash

# install 
# sudo apt install libgmp-dev libmpfr-dev libboost-dev 
# sudo apt libboost-thread-dev libboost-system-dev zlib1g-dev libblas-dev liblapack-dev

if [ $#!=1 ];then
    echo "USAGE:$0 <version-number>"
    echo "example: $0 4.14"
    exit 1
fi
cd cgal 
git pull
git archive --format=zip --prefix=CGAL-$1/ releases/CGAL-$1 > ../install/CGAL-$1.zip
cd ../install
unzip CGAL-$1.zip

cd CGAL-$1/
mkdir -p build/release
cd build/release
cmake -DCMAKE_BUILD_TYPE=Release ../..
make
