#!/bin/bash

# !!!!!!!!!!! sudo apt install liblua5.3-dev
echo "$#"
#if [ $#!=1 ];then
#    echo "USAGE:$0 <version-number>"
#    echo "example: $0 2.2"
#    exit 1
#fi


rm -fr install/p4est-$1
cd p4est 
git checkout master
git pull
git submodule init
git submodule update
git archive --format=zip --prefix=p4est-$1/ v$1 > ../install/p4est-$1.zip
cd ../install
unzip p4est-$1.zip

cd p4est-$1/
cp ../../p4est/sc/* sc/ -r
./configure --prefix=/usr/local --with-metis --enable-mpi CFLAGS="-O2 -Wall -Wno-unused-but-set-variable" LIBS=/usr/lib/x86_64-linux-gnu/liblua5.3.so
make -j8
